// types/agreementTypes.ts
// Shared TypeScript types for Tier 1 features

// ─────────────────────────────────────────────────────────────────────────────
// Maintenance Agreement Tiers
// ─────────────────────────────────────────────────────────────────────────────

export interface MaintenanceTier {
	id: string;
	companyId: string;
	name: string;
	description?: string | null;
	priceMonthly?: number | null;
	priceAnnual: number;
	billingCycle: "monthly" | "annual";
	includedVisits: number;
	discountPercent: number;
	priorityDispatch: boolean;
	includedServices: string[];
	isActive: boolean;
	createdAt: string;
	updatedAt: string;
}

export type CreateTierInput = Omit<
	MaintenanceTier,
	"id" | "createdAt" | "updatedAt"
>;
export type UpdateTierInput = Partial<CreateTierInput>;

// ─────────────────────────────────────────────────────────────────────────────
// Maintenance Agreements
// ─────────────────────────────────────────────────────────────────────────────

export type AgreementStatus =
	| "active"
	| "pending"
	| "expired"
	| "cancelled"
	| "suspended";

export interface MaintenanceAgreement {
	id: string;
	companyId: string;
	branchId?: string | null;
	customerId: string;
	tierId: string;
	status: AgreementStatus;
	billingCycle: "monthly" | "annual";
	priceLocked: number;
	startsAt: string; // ISO date
	expiresAt: string; // ISO date
	autoRenew: boolean;
	renewalNotifiedAt?: string | null;
	visitsUsed: number;
	visitsAllowed: number;
	notes?: string | null;
	createdBy?: string | null;
	cancelledAt?: string | null;
	cancellationReason?: string | null;
	createdAt: string;
	updatedAt: string;
	// Joined
	tierName?: string;
	customerName?: string;
}

export interface CreateAgreementInput {
	customerId: string;
	tierId: string;
	billingCycle?: "monthly" | "annual";
	startsAt: string;
	autoRenew?: boolean;
	notes?: string;
	branchId?: string;
}

export interface CancelAgreementInput {
	reason?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Recurring Job Schedules
// ─────────────────────────────────────────────────────────────────────────────

export type RecurringFrequency =
	| "weekly"
	| "biweekly"
	| "monthly"
	| "bimonthly"
	| "quarterly"
	| "semiannual"
	| "annual";

export interface RecurringJobSchedule {
	id: string;
	companyId: string;
	branchId?: string | null;
	customerId: string;
	agreementId?: string | null;
	title: string;
	description?: string | null;
	jobType: string;
	skillsRequired: string[];
	preferredTechId?: string | null;
	frequency: RecurringFrequency;
	cronExpression?: string | null;
	preferredTimeStart?: string | null;
	preferredTimeEnd?: string | null;
	preferredDays: string[];
	durationMinutes: number;
	nextRunAt: string;
	lastRunAt?: string | null;
	lastJobId?: string | null;
	advanceDays: number;
	isActive: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface CreateRecurringScheduleInput {
	customerId: string;
	agreementId?: string;
	title: string;
	description?: string;
	jobType: string;
	skillsRequired?: string[];
	preferredTechId?: string;
	frequency: RecurringFrequency;
	preferredTimeStart?: string;
	preferredTimeEnd?: string;
	preferredDays?: string[];
	durationMinutes?: number;
	nextRunAt: string;
	advanceDays?: number;
	branchId?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Invoices
// ─────────────────────────────────────────────────────────────────────────────

export type InvoiceStatus =
	| "draft"
	| "sent"
	| "paid"
	| "overdue"
	| "void"
	| "refunded";

export interface LineItem {
	description: string;
	quantity: number;
	unitPrice: number;
	total: number;
}

export interface Invoice {
	id: string;
	companyId: string;
	customerId: string;
	agreementId?: string | null;
	jobId?: string | null;
	invoiceNumber: string;
	status: InvoiceStatus;
	subtotal: number;
	taxAmount: number;
	discountAmount: number;
	total: number;
	dueDate?: string | null;
	paidAt?: string | null;
	paymentMethod?: string | null;
	paymentReference?: string | null;
	lineItems: LineItem[];
	notes?: string | null;
	sentAt?: string | null;
	autoGenerated: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface CreateInvoiceInput {
	customerId: string;
	agreementId?: string;
	jobId?: string;
	lineItems: LineItem[];
	taxAmount?: number;
	discountAmount?: number;
	dueDate?: string;
	notes?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Booking Requests (Customer Portal)
// ─────────────────────────────────────────────────────────────────────────────

export type BookingRequestStatus =
	| "pending"
	| "confirmed"
	| "declined"
	| "cancelled"
	| "converted";

export interface BookingRequest {
	id: string;
	companyId: string;
	branchId?: string | null;
	customerId: string;
	agreementId?: string | null;
	serviceType: string;
	description?: string | null;
	preferredDate1: string;
	preferredTime1?: string | null;
	preferredDate2?: string | null;
	preferredTime2?: string | null;
	preferredDate3?: string | null;
	preferredTime3?: string | null;
	status: BookingRequestStatus;
	convertedJobId?: string | null;
	staffNotes?: string | null;
	customerNotes?: string | null;
	createdAt: string;
	updatedAt: string;
}

export interface CreateBookingRequestInput {
	serviceType: string;
	description?: string;
	preferredDate1: string;
	preferredTime1?: "morning" | "afternoon" | "evening";
	preferredDate2?: string;
	preferredTime2?: "morning" | "afternoon" | "evening";
	preferredDate3?: string;
	preferredTime3?: "morning" | "afternoon" | "evening";
	customerNotes?: string;
	agreementId?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Review Requests
// ─────────────────────────────────────────────────────────────────────────────

export type ReviewRequestStatus =
	| "pending"
	| "sent"
	| "clicked"
	| "reviewed"
	| "opted_out"
	| "failed";

export interface ReviewRequest {
	id: string;
	companyId: string;
	jobId: string;
	customerId: string;
	channel: "sms" | "email";
	status: ReviewRequestStatus;
	scheduledFor: string;
	sentAt?: string | null;
	clickedAt?: string | null;
	reviewPlatform: string;
	messageSid?: string | null;
	createdAt: string;
	updatedAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// After-Hours Rules
// ─────────────────────────────────────────────────────────────────────────────

export type RoutingStrategy =
	| "on_call_pool"
	| "specific_tech"
	| "escalate_immediately"
	| "voicemail_queue";

export interface AfterHoursRule {
	id: string;
	companyId: string;
	branchId?: string | null;
	name: string;
	isActive: boolean;
	weekdayStart: string; // HH:MM
	weekdayEnd: string; // HH:MM
	weekendAllDay: boolean;
	holidayAllDay: boolean;
	routingStrategy: RoutingStrategy;
	onCallEmployeeIds: string[];
	surchargeFlatFlat?: number | null;
	surchargePercent?: number | null;
	autoAccept: boolean;
	notifyManager: boolean;
	managerPhone?: string | null;
	createdAt: string;
	updatedAt: string;
}

export interface CreateAfterHoursRuleInput {
	name: string;
	weekdayStart?: string;
	weekdayEnd?: string;
	weekendAllDay?: boolean;
	holidayAllDay?: boolean;
	routingStrategy: RoutingStrategy;
	onCallEmployeeIds?: string[];
	surchargeFlatFlat?: number;
	surchargePercent?: number;
	autoAccept?: boolean;
	notifyManager?: boolean;
	managerPhone?: string;
	branchId?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Escalation
// ─────────────────────────────────────────────────────────────────────────────

export interface EscalationStep {
	delayMinutes: number;
	notify: string[]; // role names or employee IDs
	channel: "sms" | "call" | "email" | "push";
	message?: string;
}

export interface EscalationTriggerConditions {
	keywords?: string[]; // match job description/type
	priority?: string[]; // job priority levels
	jobTypes?: string[];
}

export interface EscalationPolicy {
	id: string;
	companyId: string;
	branchId?: string | null;
	name: string;
	triggerConditions: EscalationTriggerConditions;
	isActive: boolean;
	steps: EscalationStep[];
	createdAt: string;
	updatedAt: string;
}

export type EscalationEventStatus =
	| "active"
	| "resolved"
	| "cancelled"
	| "timed_out";

export interface EscalationEvent {
	id: string;
	companyId: string;
	jobId: string;
	policyId?: string | null;
	currentStep: number;
	status: EscalationEventStatus;
	triggeredAt: string;
	resolvedAt?: string | null;
	resolvedBy?: string | null;
	resolutionNotes?: string | null;
	notificationLog: Array<{
		step: number;
		sentAt: string;
		recipient: string;
		channel: string;
		success: boolean;
	}>;
	createdAt: string;
	updatedAt: string;
}
