/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/small-air-conditioner-unit.glb --transform 
Files: public/small-air-conditioner-unit.glb [174.42KB] > C:\Users\Nathan\Git\1st-period-isp-tech-to-customer\small-air-conditioner-unit-transformed.glb [19.17KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF(
		"/small-air-conditioner-unit-transformed.glb"
	);
	return (
		<group {...props} dispose={null}>
			<group position={[0, 0, -0.638]}>
				<mesh geometry={nodes.Cube004.geometry} material={materials.Plastic} />
				<mesh
					geometry={nodes.Cube004_1.geometry}
					material={materials["Plastic black"]}
				/>
				<mesh
					geometry={nodes.Cube004_2.geometry}
					material={materials.FrontPlastic}
				/>
				<mesh geometry={nodes.Cube004_3.geometry} material={materials.Chrome} />
			</group>
		</group>
	);
}

useGLTF.preload("/small-air-conditioner-unit-transformed.glb");
